### ISSUE TITLE
Workflow improvements

### ISSUE THREAD

**Issue by object-Object** [HexxyCraft/modpack#32]
- [x] Require Actions to pass before merging to master
- [x] Fix the name of the version check action
- [x] Schedule merges to master every day at 2:45 pm UTC
- [x] Change the daily restart to always bring the server offline at 3 pm UTC (account for DST)
